# Redundant with /etc/mpv/mpv.conf:
hwdec=vaapi

# Local customization:
osd-duration=5000
osd-on-seek=msg-bar
sub-file-paths=/home/playback/.cache/playback/subs
sub-auto=all

# HDR peak calculations kill output frame rates. See "intel_gpu_top" and
# https://github.com/mpv-player/mpv/issues/8981
hdr-compute-peak=no

# To let the audio initialize
pause=yes
# It may be possible to use --audio-wait-open=<secs> instead since we're
# using "audio-stream-silence=yes" below.

# Does adding this caching help with .ts playback audio drop-out? Nope.
demuxer-max-bytes=500M
demuxer-max-back-bytes=100M
cache=yes
cache-secs=120
# Does this help?
audio-buffer=2
#audio-buffer=5
#ao-alsa-buffer-time=500000
# Or this?
#ao-null-fallback=yes
# Debugging for the audio drops?
#msg-level=ao=debug

# https://www.reddit.com/r/mpv/comments/16pe68f/regarding_videosyncdisplayresample/
# Is this actually good for mismatched frame/vsync rates? Oh god, it's horrible.
#video-sync=display-resample
#interpolation=yes
# Enabling "smoothmotion" to troll Kirsten. Doesn't seem to work?
#tscale=oversample

# Scalers/Shaders
# https://artoriuz.github.io/blog/mpv_upscaling.html
# https://github.com/xzpyth/mpv-config/blob/main/mpv.conf
#scale=ewa_lanczossharp
# Deprecated?
scale=ewa_lanczos
scale-blur=0.9812505644269356

# pipewire has lost all the passthrough?!
# mpv --audio-device=help
# Solution appears to be:
audio-device=alsa/hdmi
# audio passthrough on HDMI or SPDIF
audio-spdif=ac3,dts,dts-hd,eac3,truehd
# Make sure the Receiver is in STRAIGHT mode or it will try
# to up-sample.
audio-channels=auto
#audio-channels=7.1,5.1,stereo

# pipewire has cranked down the volume by default (?!)
# https://www.reddit.com/r/mpv/comments/lkxykh/how_to_play_videos_in_51_surround_sound/
volume=80
volume-max=150             # maximum volume in %, everything above 100 results in amplification
#ad-lavc-downmix=no
#af=surround:chl_out=5.1   # audio filter for mixing to surround (5.1)

# Without this, pauses and skips will stop the audio stream and the driver
# may disconnect the HDMI output, causing playback to skip audio.
audio-stream-silence=yes                   # fix audio popping on random seek
# Above wasn't sufficient! This seemed to fix yet more corner-cases:
# $ cat /etc/modprobe.d/snd-hda-intel.conf 
# options snd-hda-intel power_save=0 power_save_controller=N

#msg-level=ao=debug,ad=debug
