#!/bin/bash
CACHE=~/.cache/playback/thumbnails
EXT=png

MEDIA=$(realpath "$1")

HASH=$(echo -n "$MEDIA" | sha256sum | awk '{print $1}')
INDEX=$(echo "$HASH" | cut -c-2)
mkdir -p "$CACHE"/$INDEX
NEW="$CACHE"/$INDEX/$HASH.new.$EXT
THUMB="$CACHE"/$INDEX/$HASH.$EXT
JSON="$THUMB.json"
BASE_EXT=$(echo "$MEDIA" | awk -F. '{print $NF}')
if [ "$BASE_EXT" == "$MEDIA" ]; then
	# No extension, just give up.
	echo "Giving up, no extension: $MEDIA" >&2
	exit 1
fi
# TODO: create this safely
LINK="/tmp/thumbnailer-$$".$BASE_EXT

thumb_frame()
{
	local frame="$1"
	mpv "$LINK" --really-quiet --no-audio --sid=no --hwdec=no --vf=scale=-1:720 --start="$frame" --frames=1 --o="$NEW"
}

do_thumbnail()
{
	ln -sf "$1" "$LINK"
	if ! thumb_frame 0 ; then
		rm -f "$LINK" "$NEW"
		return
	fi

	# Check for a boring thumbnail (i.e. mostly the same color)
	COLORS=5
	COUNT=$(convert "$NEW" +dither -colors "$COLORS" -unique-colors txt: | grep -v '^#' | wc -l)
	if [ $COUNT -lt $COLORS ] ; then
		# Pick a later image?
		if ! thumb_frame 60 ; then
			rm -f "$LINK" "$NEW"
			return
		fi
	fi

	rm -f "$LINK"
	mv "$NEW" "$THUMB"
}

do_json()
{
	ln -sf "$1" "$LINK"
	if mediainfo --Output=JSON "$LINK" > "$NEW".json ; then
		mv "$NEW".json "$JSON"
	fi
	rm -f "$LINK"
}

if [ ! -e "$THUMB" ] || [ "$MEDIA" -nt "$THUMB" ]; then
	do_thumbnail "$MEDIA"
fi

if [ ! -e "$JSON" ] || [ "$MEDIA" -nt "$JSON" ]; then
	do_json "$MEDIA"
fi

echo "$THUMB"
